### ISSUE TITLE
Runtime decryption not working

### ISSUE THREAD

**Issue by perfectime94** [ximtech/jasypt-encrypt-plugin#1]
Hello, im using latest version of plugin with springboot 3.0.4 and jdk 19, when i run decryptProperties or encryptProperties task with environment variable JASYPT_ENCRYPTOR_PASSWORD they work flawlessly but when i run the app with bootRun having the same environment variable the properties aren't decrypted at runtime, im using CommandLineRunner to print the property

this is  the sample project im using to test it [encrypt.zip](https://github.com/ximtech/jasypt-encrypt-plugin/files/10936395/encrypt.zip)

**Comment by ximtech** [comment]
Hi. For decrypting parameters in runtime you need additional library for spring boot application: [link](https://github.com/ulisesbocchio/jasypt-spring-boot)
![image](https://user-images.githubusercontent.com/25764227/224274957-0cd80885-e8b7-4580-aff6-78427519ce07.png)
Then all should work fine. As we can see in the console that encryptor has been initialized correctly.
![image](https://user-images.githubusercontent.com/25764227/224275788-1c6e2655-f2a5-4a95-96c5-d97939af09d3.png)
*PS:* Make sure that same encryption key is used in `encryptProperties/decryptProperties` gradle task (in intellij it can be fetched from old .run configuration)
Debug password with log message: `println "Password: " + System.getenv('JASYPT_ENCRYPTOR_PASSWORD')`

**Comment by perfectime94** [comment]
thanks a lot, i added the starter and its working on runtime.

Again thanks for ur work on this plugin
