### ISSUE TITLE
minor miss spell on readme

### ISSUE THREAD

**Issue by Lee-Minjea** [ximtech/jasypt-encrypt-plugin#5]
Hello my friend

I found a minor miss spell on README.md

https://github.com/ximtech/jasypt-encrypt-plugin/blob/b02908bba5d387f26b52f8c0321b80e5205c5336/README.md?plain=1#L42

This is supposed to be 
```
apply plugin: io.github.jasypt.encrypt.JasyptPlugin
```

thank you for nice and neat plugin, this saves my hours of work.

**Comment by ximtech** [comment]
Fixed. Thank you!
