### ISSUE TITLE
Encrypted password not decrypting to start the application

### ISSUE THREAD

**Issue by vivekananda501** [ximtech/jasypt-encrypt-plugin#6]
Hi,

When I run `gradle encryptProperties --password=tmp` in the project folder, it encrypted properly which is in `application.yml` from the command line after the encryption the application does not start.

Can you help me out what I'm missing.
Attached the code [sample.zip](https://github.com/user-attachments/files/16782043/sample.zip)

**Comment by vivekananda501** [comment]
@ximtech, do you have time to check this.

**Comment by ximtech** [comment]
Hi! For decryption in runtime you need to add dependency in build.gradle
`implementation "com.github.ulisesbocchio:jasypt-spring-boot-starter:3.0.5"`
Plugin provides only compile time encryption/decryption

**Comment by vivekananda501** [comment]
Thanks @ximtech for the update. Is there any online tool to encrypt/decrypt with different algorithms as I'm unable to do from the command line.

**Comment by ximtech** [comment]
When plugin parse configuration file it also takes provided jasypt config if it present. So you can change encrypt/decrypt parameters directly in application yaml/properties. Please check the example in doc:  [link](https://github.com/ximtech/jasypt-encrypt-plugin?tab=readme-ov-file#jasypt-configuration)

**Comment by vivekananda501** [comment]
Thank you.
